# Generated by Django 5.1.7 on 2025-04-01 00:12

from django.db import migrations


def set_default_capacity(apps, schema_editor):
    SportClass = apps.get_model("reservations", "SportClass")
    for sport_class in SportClass.objects.all():
        if sport_class.max_capacity == 10:  # Only if it's the default value
            sport_class.max_capacity = 20  # New default value
            sport_class.save()


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_alter_sportclass_max_capacity"),
    ]

    operations = [migrations.RunPython(set_default_capacity)]
